export default {
  default: [
    "Canard",
    "Ambulance",
    "Quelqu'un",
    "Porte",
    "Fenêtre",
    "Oublier",
    "Chanter",
    "Fête",
    "Arbre",
    "Dent",
    "Rire",
    "Cheveux",
    "Chaussure",
    "Hasard",
    "Téléphone",
    "Imiter",
    "Exploser",
    "Élastique",
    "Cadeau",
    "Chaussette",
    "Bébé",
    "Pantalon",
    "Chapeau",
    "Code secret",
    "Clin d'oeil",
    "Hélicoptère",
    "Taxi",
    "Malheureusement",
    "Venu du ciel",
    "Câlin",
    "Lit",
    "Danser",
    "Déguisement",
    "Malette",
    "Arc en ciel",
    "Rendez-vous",
    "Attraper",
    "Poule",
    "Oeuf",
    "Vaisseau spatial",
    "Lumière",
    "Catastrophe",
    "Voler",
    "Extra-terrestre",
    "Robot",
    "Avaler",
    "Objet",
    "Projet",
    "Bêtise",
    "Discuter",
    "S'ennuyer",
    "Triste",
    "Joyeux",
    "Entendre",
  ],
  adventure: [
    "Dragon",
    "Licorne",
    "Mystérieux",
    "Passage secret",
    "Frapper",
    "Quête",
    "Magicien",
    "Feu",
    "Embuscade",
    "Fort",
    "Pigeon",
    "Double maléfique",
    "Musique épique",
    "Tournoi",
    "Chevaucher",
    "Grotte",
    "Foncer dans le tas",
    "Vent",
    "Sac à dos",
    "Pelle",
    "Trésor",
    "Voleur",
    "Pirate",
    "Clé",
    "Complot",
    "Trou",
    "Messager",
    "Guerrier",
    "Marchand",
    "Amoureux",
    "Coffre",
    "Minuscule",
    "Gigantesque",
    "Pouvoir",
    "A quatre pattes",
    "Symboles",
    "Héros",
    "Transformer",
    "Botte",
    "Danger",
    "Inconnu",
    "Incroyable",
    "Très loin",
    "Mystérieux",
    "Méchant",
    "Gentil",
    "Téléportation",
    "Démoniaque",
    "Serrure",
    "Épée",
    "Sauvage",
    "Grenouille",
    "Libérer",
    "Sept",
  ],
  horror: [
    "Vivant",
    "Vampire",
    "Malédiction",
    "Sombre",
    "Tombe",
    "Fantôme",
    "Sang",
    "Masque",
    "Blague",
    "Poison",
    "Dans le noir total",
    "Paniquer",
    "Pleurer",
    "Prendre une photo",
    "Tête",
    "Ombre",
    "Enfermer",
    "Prédiction",
    "Froid",
    "Couteau",
    "Squelette",
    "Inquiétant",
    "Brouillard",
    "Main",
    "Fermer les yeux",
    "Voix dans la tête",
    "Odeur désagréable",
    "Monstre",
    "Victime",
    "Esprit",
    "Se retrouver seul",
    "Piège",
    "Hypnotiser",
    "Invisible",
    "Blessure",
    "Serpent",
    "Avec trois yeux",
    "Gluant",
    "Cercueil",
    "Grimoire",
    "Secret",
    "Potion",
    "Sorcière",
    "Tomber",
    "Crier",
    "Avoir peur",
    "Prendre son courage à deux mains",
    "Chaton",
    "Pattes velues",
    "Docteur",
    "Tronçonneuse",
    "Étrange",
    "Apparaître",
    "Disparaître",
  ],
};
